#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
  CREATE DATABASE $DB_NAME OWNER $DB_USERNAME;
  GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;
  SET timezone TO "$TZ";
  \c $DB_NAME
  ALTER DATABASE $DB_NAME SET timezone TO "$TZ";
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL
