version: '3'

services:
  database:
    image: postgres:14.1-alpine
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    container_name: database
    restart: always
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - db:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql.conf
      - ./01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - /var/lib/pgadmin:/var/lib/pgadmin

networks:
  postgres-network:
    driver: bridge

volumes:
  db:
    driver: local
